name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token
          heroku container:login

      - name: Set Heroku Stack
        env:
          HEROKU_APP_NAME: segment-case-study
        run: |
          heroku stack:set container --app $HEROKU_APP_NAME

      - name: Build, Push, and Release Docker image
        env:
          HEROKU_APP_NAME: segment-case-study
        run: |
          docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
          heroku container:release web --app $HEROKU_APP_NAME

